# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      # environment setting created by JEFWorks-Lab
      # GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # R_KEEP_PKG_SOURCE: yes
      # R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      # _R_CHECK_CRAN_INCOMING_REMOTE_: false
      # _R_CHECK_FORCE_SUGGESTS_: false
      
      # Bioconductor recommended environment (https://contributions.bioconductor.org/general.html)
      # https://www.rdocumentation.org/packages/base/versions/3.5.1/topics/Startup
      # https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Checking-and-building-packages
      # https://cran.r-project.org/doc/manuals/r-devel/R-ints.html#Tools
      _R_CHECK_FORCE_SUGGESTS_: true
      _R_CHECK_RD_LINE_WIDTHS_: true
      _R_CHECK_EXECUTABLES_: false
      _R_CHECK_EXECUTABLES_EXCLUSIONS_: false
      _R_CHECK_FF_DUP_: true
      _R_CHECK_VC_DIR_: true
      _R_CHECK_PKG_SIZES_: true
      _R_CHECK_PKG_SIZES_THRESHOLD_: 5
      _R_CHECK_REPLACING_IMPORTS_: true
      _R_CHECK_TIMINGS_: "0"
      _R_CHECK_INSTALL_DEPENDS_: true
      _R_CHECK_SUGGESTS_ONLY_: true
      _R_CHECK_NO_RECOMMENDED_: true
      _R_CHECK_CODE_ASSIGN_TO_GLOBALENV_: true
      _R_CHECK_CODE_ATTACH_: true
      _R_CHECK_CODE_DATA_INTO_GLOBALENV_: true
      _R_CHECK_DOT_FIRSTLIB_: true
      _R_CHECK_DEPRECATED_DEFUNCT_: true
      _R_CHECK_TOPLEVELFILES_: true
      _R_CHECK_LIMIT_CORES_: true
      _R_CHECK_CODE_USAGE_VIA_NAMESPACES_: true
      _R_CHECK_S3_METHODS_NOT_REGISTERED_: true
      _R_CHECK_OVERWRITE_REGISTERED_S3_METHODS_: true
      _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_: true
      _R_CHECK_TESTS_NLINES_: 20
      _R_CHECK_NATIVE_ROUTINE_REGISTRATION_: true
      _R_CHECK_NO_STOP_ON_TEST_ERROR_: true
      _R_CHECK_PRAGMAS_: true
      _R_CHECK_COMPILATION_FLAGS_: true
      _R_CHECK_R_DEPENDS_: "warn"
      _R_CHECK_SERIALIZATION_: true
      _R_CHECK_R_ON_PATH_: true
      _R_CHECK_PACKAGES_USED_IN_TESTS_USE_SUBDIRS_: true
      _R_CHECK_SHLIB_OPENMP_FLAGS_: true
      _R_CHECK_CONNECTIONS_LEFT_OPEN_: true
      _R_CHECK_FUTURE_FILE_TIMESTAMPS_: true
      _R_CHECK_LENGTH_1_CONDITION_ : package:_R_CHECK_PACKAGE_NAME_
      _R_CHECK_LENGTH_1_LOGIC2_: package:_R_CHECK_PACKAGE_NAME_
      IS_BIOC_BUILD_MACHINE: true
      _R_CHECK_NEWS_IN_PLAIN_TEXT_: true
      R_DEFAULT_INTERNET_TIMEOUT: 600
      BIOCPARALLEL_WORKER_NUMBER: 4
      OMP_THREAD_LIMIT: 2
      OMP_NUM_THREADS: 2
      KMP_DEVICE_THREAD_LIMIT: 2
      KMP_TEAMS_THREAD_LIMIT: 2
      _R_COMPARE_LANG_OBJECTS: eqonly
      
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:	
          error-on: '"error"'
          upload-snapshots: true

